### ISSUE TITLE
[SCAN] sub-01_ses-001

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/friends-fix#1]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.
