### ISSUE TITLE
[SCAN] sub-06_ses-002

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends-fix#3]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

Biopac : pulsation ok, respiration ok, ECG a bit noisy (ok during setup)
EDA around 3.75 (around 2 during setup, gain level at lowest position, no further investigation)

eyetracking calibration ok

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

freezing happened often during run.

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 notes

during calibration, a fixation pot was missed (right down corner). I decided to continue as the rest seem ok ?
 freezing happened often during run.

### task-friends_run-03 completion

- [ ] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.
