### ISSUE TITLE
[SCAN] sub-06_ses-003

### ISSUE THREAD

**Issue by pravishsainath** [courtois-neuromod/friends-fix#4]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

- The eye tracker was blurry despite maximum sharpness.
- GSR signal was always zero

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 issues

physio signal quality issue

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 issues

physio signal quality issue

### task-friends_run-03 completion

- [ ] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.
