### ISSUE TITLE
[SCAN] sub-06_ses-004

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends-fix#5]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

Biosignals : 
pulsation, ECG, respiration OK during setup

EDA around 7.5 during setup, and around 5 in the scanner

Eyetracker setup ok

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

recurrent freezing of eyetracking video

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 notes

recurrent freezing of eyetracking video

### task-friends_run-03 completion

- [ ] series was completed.

### task-friends_run-03 notes

recurrent freezing of eyetracking video

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-04 notes

one missing fixation point (down - left) after doing the eyetracking calibration.
recurrent freezing of eyetracking video
