### ISSUE TITLE
[SCAN] sub-01_ses-004

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends-fix#6]
### Setup

- [x] biopac
- [x] sensimetrics
- [x] eyetracker

### general notes

Biopac signals all good (Pulsation, ECG, respiration, EDA)
EDA around 7-8 during scanning, (12 during setup)

Eyetracking setup ok

### task-friends_run-01 completion

- [x] series was completed.

### task-friends_run-02 completion

- [x] series was completed.

### task-friends_run-03 completion

- [x] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.
